 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/species", type: :request do
  
  # Species. As you add validations to Species, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Species.create! valid_attributes
      get species_index_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      species = Species.create! valid_attributes
      get species_url(species)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_species_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      species = Species.create! valid_attributes
      get edit_species_url(species)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Species" do
        expect {
          post species_index_url, params: { species: valid_attributes }
        }.to change(Species, :count).by(1)
      end

      it "redirects to the created species" do
        post species_index_url, params: { species: valid_attributes }
        expect(response).to redirect_to(species_url(Species.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Species" do
        expect {
          post species_index_url, params: { species: invalid_attributes }
        }.to change(Species, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post species_index_url, params: { species: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested species" do
        species = Species.create! valid_attributes
        patch species_url(species), params: { species: new_attributes }
        species.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the species" do
        species = Species.create! valid_attributes
        patch species_url(species), params: { species: new_attributes }
        species.reload
        expect(response).to redirect_to(species_url(species))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        species = Species.create! valid_attributes
        patch species_url(species), params: { species: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested species" do
      species = Species.create! valid_attributes
      expect {
        delete species_url(species)
      }.to change(Species, :count).by(-1)
    end

    it "redirects to the species list" do
      species = Species.create! valid_attributes
      delete species_url(species)
      expect(response).to redirect_to(species_index_url)
    end
  end
end
